### ISSUE TITLE
Error bij het starten van de  server

### ISSUE THREAD

**Issue by Naddybs** [KaanKalmi/server-side-rendering-server-side-website#1]
<img width="1047" alt="Schermafbeelding 2024-03-05 om 20 40 22" src="https://github.com/KaanKalmi/server-side-rendering-server-side-website/assets/144009698/72aa7b46-f487-4a76-a737-d50ded9ba534">

Je gaf aan dat je een probleem had bij het starten van je server. Je kreeg namelijk de bovenstaande error te zien. "cannot find module" geeft aan dat node.js het opgegeven bestand 'app.js' niet kan vinden. 

In de package.json bestand stond aangegeven dat het startscript  (npm start) het bestand app.js moet uitvoeren. Dit kan niet omdat het daadwerkelijke bestand waar de servercode in staat server.js heet en niet app.js.

Het probleem kan je dus oplossen door in de package.json het startscript aan te passen naar server.js zodat het nu het juiste bestand uitvoert. Als je dan het npm start commando uitvoert  de juiste servercode wordt opgestart en niet de ✨non existent✨ app.js.

<img width="1178" alt="Schermafbeelding 2024-03-05 om 20 49 22" src="https://github.com/KaanKalmi/server-side-rendering-server-side-website/assets/144009698/3a661ae0-9005-4fc7-ad33-158d2ba05317">

**Comment by KaanKalmi** [comment]
_✨non existent✨_

Hier moet een - tussen het is non-existent!

![image](https://github.com/KaanKalmi/server-side-rendering-server-side-website/assets/144000125/0bcf22d8-bf7e-424d-b80c-3f48163aa68b)

**Comment by Naddybs** [comment]
> _✨non existent✨_
> 
> Hier moet een - tussen het is non-existent!
> 
> ![image](https://private-user-images.githubusercontent.com/144000125/310260584-0bcf22d8-bf7e-424d-b80c-3f48163aa68b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Njg2OTAsIm5iZiI6MTcwOTY2ODM5MCwicGF0aCI6Ii8xNDQwMDAxMjUvMzEwMjYwNTg0LTBiY2YyMmQ4LWJmN2UtNDI0ZC1iODBjLTNmNDgxNjNhYTY4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxOTUzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWQ5YTI3Njk0NzZlNTkyM2Y1ZWRhMGZkYTVjOGU2ZjljNGU0MTlhNmIzYTgzYzQyYTI5NTk1Y2UxNWQ2ZGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J8E8XO7xnxqXHKN2LGH6a2h6D-Bilyzxe0Yc8qvq6xk)

Bedankt voor de feedback! Is dat niet toevallig een synoniem voor je brein cellen?

**Comment by KaanKalmi** [comment]
nee het is een synoniem dat onze band beschrijft!
